# Initialize lists for demographics
n_tracer <- list()
age_tracer <- list()
age_sd_tracer <- list()
male_tracer <- list()
n_vr_tracer<-list()
n_apoe_tracer <- list()
n_apoe_non_c_tracer <- list()
n_apoe_homo_tracer <- list()
n_apoe_hetero_tracer <- list()
n_cn_tracer <- list()
n_mci_tracer <- list()
n_dementia_tracer <- list()
n_cn_cdr_tracer <- list()
n_patient_cdr_tracer <- list()

# Initialize lists for cognition
n_dx_tracer <- list()
n_cdr_tracer <- list()
cdr_mean_tracer <- list()
cdr_sd_tracer <- list()
n_mmse_tracer <- list()
mmse_mean_tracer <- list()
mmse_sd_tracer <- list()

# Initialize lists for GMM
gauss1_tracer <- list()
gauss1_tracer_ci_low <- list()
gauss1_tracer_ci_upp <- list()
gauss2_tracer <- list()
gauss2_tracer_ci_low <- list()
gauss2_tracer_ci_upp <- list()
gausssd1_tracer <- list()
gausssd1_tracer_ci_low <- list()
gausssd1_tracer_ci_upp <- list()
gausssd2_tracer <- list()
gausssd2_tracer_ci_low <- list()
gausssd2_tracer_ci_upp <- list()
cutoff_gmm_tracer <- list()
cutoff_gmm_tracer_ci_low <- list()
cutoff_gmm_tracer_ci_upp <- list()
cutoff_gmm_double_low_0p5_tracer <- list()
cutoff_gmm_double_low_0p5_tracer_ci_low <- list()
cutoff_gmm_double_low_0p5_tracer_ci_upp <- list()
cutoff_gmm_double_high_0p5_tracer <- list()
cutoff_gmm_double_high_0p5_tracer_ci_low <- list()
cutoff_gmm_double_high_0p5_tracer_ci_upp <- list()
cutoff_gmm_double_low_0p6_tracer <- list()
cutoff_gmm_double_low_0p6_tracer_ci_low <- list()
cutoff_gmm_double_low_0p6_tracer_ci_upp <- list()
cutoff_gmm_double_high_0p6_tracer <- list()
cutoff_gmm_double_high_0p6_tracer_ci_low <- list()
cutoff_gmm_double_high_0p6_tracer_ci_upp <- list()
cutoff_gmm_double_low_0p7_tracer <- list()
cutoff_gmm_double_low_0p7_tracer_ci_low <- list()
cutoff_gmm_double_low_0p7_tracer_ci_upp <- list()
cutoff_gmm_double_high_0p7_tracer <- list()
cutoff_gmm_double_high_0p7_tracer_ci_low <- list()
cutoff_gmm_double_high_0p7_tracer_ci_upp <- list()
cutoff_gmm_double_low_0p8_tracer <- list()
cutoff_gmm_double_low_0p8_tracer_ci_low <- list()
cutoff_gmm_double_low_0p8_tracer_ci_upp <- list()
cutoff_gmm_double_high_0p8_tracer <- list()
cutoff_gmm_double_high_0p8_tracer_ci_low <- list()
cutoff_gmm_double_high_0p8_tracer_ci_upp <- list()
cutoff_gmm_double_low_0p9_tracer <- list()
cutoff_gmm_double_low_0p9_tracer_ci_low <- list()
cutoff_gmm_double_low_0p9_tracer_ci_upp <- list()
cutoff_gmm_double_high_0p9_tracer <- list()
cutoff_gmm_double_high_0p9_tracer_ci_low <- list()
cutoff_gmm_double_high_0p9_tracer_ci_upp <- list()

# Initialize lists for Visual Read (VR)
cutoff_kappa_tracer <- list()
cutoff_kappa_tracer_ci_low <- list()
cutoff_kappa_tracer_ci_upp <- list()
kappa_tracer <- list()
kappa_tracer_ci_low <- list()
kappa_tracer_ci_upp <- list()
cutoff_youden_tracer <- list()
cutoff_youden_tracer_ci_low <- list()
cutoff_youden_tracer_ci_upp <- list()
auc_roc_tracer<-list()
auc_roc_tracer_ci_low<-list()
auc_roc_tracer_ci_upp<-list()
cutoff_95sens_tracer <- list()
cutoff_95sens_tracer_ci_low <- list()
cutoff_95sens_tracer_ci_upp <- list()
cutoff_95spec_tracer <- list()
cutoff_95spec_tracer_ci_low <- list()
cutoff_95spec_tracer_ci_upp <- list()
cutoff_90sens_tracer <- list()
cutoff_90sens_tracer_ci_low <- list()
cutoff_90sens_tracer_ci_upp <- list()
cutoff_90spec_tracer <- list()
cutoff_90spec_tracer_ci_low <- list()
cutoff_90spec_tracer_ci_upp <- list()
n_vr_positive_tracer <- list()
n_vr_negative_tracer <- list()

# Initialize lists for CL raw
cl_male_tracer <- list()
cl_female_tracer <- list()
cl_sd_male_tracer <- list()
cl_sd_female_tracer <- list()
cl_apoe_non_c_tracer <- list()
cl_sd_apoe_non_c_tracer <- list()
cl_apoe_homo_tracer <- list()
cl_sd_apoe_homo_tracer <- list()
cl_apoe_hetero_tracer <- list()
cl_sd_apoe_hetero_tracer <- list()
cl_vr_positive_tracer <- list()
cl_sd_vr_positive_tracer <- list()
cl_vr_negative_tracer <- list()
cl_sd_vr_negative_tracer <- list()

# Initialize lists for CDR
cl_cdr_0_tracer <- list()
cl_cdr_0p5_tracer <- list()
cl_cdr_more1_tracer <- list()
cl_sd_cdr_0_tracer <- list()
cl_sd_cdr_0p5_tracer <- list()
cl_sd_cdr_more1_tracer <- list()
cl_n_cdr_0_tracer <- list()
cl_n_cdr_0p5_tracer <- list()
cl_n_cdr_more1_tracer <- list()
